"""add username to users

Revision ID: 7dd707264b72
Revises: 5ac2c6c46f19
Create Date: 2025-11-12 11:29:15.993889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd707264b72'
down_revision: Union[str, Sequence[str], None] = '5ac2c6c46f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False), schema='auth')
    op.create_unique_constraint(None, 'users', ['username'], schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='auth', type_='unique')
    op.drop_column('users', 'username', schema='auth')
    # ### end Alembic commands ###
